pull_request_rules:
  - name: self-assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{ author }}"
  - name: automatic merge when not WIP, CI passes, and at least 1 approving review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=gitguardian
      - check-success=nixci
      - base=main
      - label!=work-in-progress
    actions:
      queue:
        name: default
queue_rules:
  - name: default
    merge_method: fast-forward
    update_method: rebase
    update_bot_account: cameronraysmith
