contact_links:
  - name: questions
    url: https://github.com/cameronraysmith/nixpod-home/discussions
    about: please post and host discussion in https://github.com/cameronraysmith/nixpod-home/discussions
