name: 'Tag, Build, and Push Container'
description: 'Shared steps to tag, build, and push container'
inputs:
  registry:
    description: 'Container registry'
    required: true
  image-name:
    description: 'Image name'
    required: true
  containerfile-path:
    description: 'Containerfile path'
    required: true
  push-condition:
    description: 'Condition to push'
    required: true
    default: 'false'
  github-token:
    description: 'GitHub Token for logging in to the container registry'
    required: true
  build-args:
    description: 'Build arguments'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: "Print github context"
      run: |
        echo "      EVENT_NAME:" "$GITHUB_EVENT_NAME"
        echo "             REF:" "$GITHUB_REF"
        echo "       full_name: ${{ github.event.repository.full_name }}"
        echo "      repository: ${{ github.repository }}"
        echo "repository_owner: ${{ github.repository_owner }}"
        echo "  default_branch: ${{ github.event.repository.default_branch }}"
        echo "REPOSITORY_OWNER:" "$GITHUB_REPOSITORY_OWNER"
        echo "        REF_NAME:" "$GITHUB_REF_NAME"
        echo "        HEAD_REF:" "$GITHUB_HEAD_REF"
        echo "        BASE_REF:" "$GITHUB_BASE_REF"
        echo "             SHA:" "$GITHUB_SHA"
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # ratchet:docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # ratchet:docker/setup-buildx-action@v3

    - name: Log in to container registry
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # ratchet:docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract github metadata for docker labels
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # ratchet:docker/metadata-action@v5
      with:
        context: git
        images: |
          ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=,format=long

    - name: Print Generated Tags
      run: |
        echo "Generated tags: ${{ steps.meta.outputs.tags }}"
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # ratchet:docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.containerfile-path }}
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push-condition }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
