name: "CD"
on:
  workflow_dispatch:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
jobs:

  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29" # v4
        with:
          ref: ${{ github.ref }}
      - uses: "DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988" # ratchet:DeterminateSystems/nix-installer-action@main
      - uses: "DeterminateSystems/flakehub-push@925b381813a62a3ff2075fb58e1263965d086f6b" # ratchet:DeterminateSystems/flakehub-push@main
        with:
          visibility: "public"

  debnix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ github.ref }}
      - name: Tag Build and Push Testing Container
        uses: ./.github/actions/tag-build-push-container
        with:
          registry: ghcr.io
          image-name: ${{ github.repository_owner }}/${{ github.job }}
          containerfile-path: "containers/Containerfile.${{ github.job }}"
          push-condition: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  nixpod:
    needs: [debnix]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ github.ref }}
      - name: Tag Build and Push Testing Container
        uses: ./.github/actions/tag-build-push-container
        with:
          registry: ghcr.io
          image-name: ${{ github.repository_owner }}/${{ github.job }}
          containerfile-path: "containers/Containerfile.${{ github.job }}"
          push-condition: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
