name: "CD"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "beta"

jobs:

  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.semantic-release.outputs.new_release_version }}
      git-tag: ${{ steps.semantic-release.outputs.new_release_git_tag }}
      released: ${{ steps.semantic-release.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Get semantic-release version
        shell: sh
        id: semantic-release-version
        run: echo version=$(npm view @cihelper/semanticrelease-preset-generic dependencies.semantic-release) >> $GITHUB_OUTPUT

      - name: Run semantic-release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: ${{ steps.semantic-release-version.outputs.version }}
          extra_plugins: "@cihelper/semanticrelease-preset-generic@1"
          extends: "@cihelper/semanticrelease-preset-generic"

  publish:
    needs: [release]
    runs-on: "ubuntu-latest"
    if: ${{ needs.release.outputs.released == 'true' }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29" # v4
        with:
          ref: ${{ github.ref }}
      - uses: "DeterminateSystems/nix-installer-action@75ffa7fc743135e1db864b699d78402ccc8ed988" # ratchet:DeterminateSystems/nix-installer-action@main
      - uses: "DeterminateSystems/flakehub-push@925b381813a62a3ff2075fb58e1263965d086f6b" # ratchet:DeterminateSystems/flakehub-push@main
        with:
          visibility: "public"
          tag: ${{ needs.release.outputs.git-tag }}

  debnix:
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.released == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ needs.release.outputs.git-tag }}
      - name: Tag Build and Push Testing Container
        uses: ./.github/actions/tag-build-push-container
        with:
          registry: ghcr.io
          image-name: ${{ github.repository_owner }}/${{ github.job }}
          containerfile-path: "containers/Containerfile.${{ github.job }}"
          push-condition: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  nixpod:
    needs: [release, debnix]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ needs.release.outputs.git-tag }}
      - name: Tag Build and Push Testing Container
        uses: ./.github/actions/tag-build-push-container
        with:
          registry: ghcr.io
          image-name: ${{ github.repository_owner }}/${{ github.job }}
          containerfile-path: "containers/Containerfile.${{ github.job }}"
          push-condition: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
