name: "CD"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft the release notes
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # ratchet:release-drafter/release-drafter@v6
        with:
          publish: true
          tag: v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29" # v4
      - uses: "DeterminateSystems/nix-installer-action@8cdf194da984e4f12b2f8c36d1fa107c1dd67f5c" # ratchet:DeterminateSystems/nix-installer-action@main
      - uses: "DeterminateSystems/flakehub-push@925b381813a62a3ff2075fb58e1263965d086f6b" # ratchet:DeterminateSystems/flakehub-push@main
        with:
          visibility: "public"
          rolling: true
