name: Labeler

on:
  push:
    branches:
      - main

jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6
        with:
          skip-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
