name: PR Fast-forward Merge
on:
  issue_comment:
    types: [created, edited]

env:
  GITHUB_ACTOR: ${{ vars.FAST_FORWARD_ACTOR }}
  GITHUB_TOKEN: ${{ secrets.FAST_FORWARD_PAT }}

jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: fast-forward merge
        uses: sequoia-pgp/fast-forward@e2c6fb52f977408912b000ad4577a669f1c4f5fe # ratchet:sequoia-pgp/fast-forward@main
        with:
          merge: true
          comment: on-error
