name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:

  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@afe4b67b57b8ab0908e4767109a5342003639e2e # ratchet:anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          PRERELEASE: true

  release:
    needs: tag
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft the release notes
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # ratchet:release-drafter/release-drafter@v6
        with:
          publish: true
          tag: outputs.tag.new_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
